name: Cypress Tests - general_project

on:
  push:
    branches:
      - main


jobs:
  general_project-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.13.1

      - name: Install dependencies
        run: npm install
        working-directory: ./general_project

      - name: Lock permissions
        run: chmod +x node_modules/.bin/cypress

      - name: Run Cypress tests 
        run: npm run cypress:headless
        working-directory: ./general_project